# meta-sdv - SDV Zone Controller Custom Layer
# Layer for Heterogeneous SDV (QRB2210 + STM32U585) - Yocto Kirkstone
# Maintainer: SDV Team <sdv@example.com>

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sdv"
BBFILE_PATTERN_sdv = "^${LAYERDIR}/"
BBFILE_PRIORITY_sdv = "7"

# 의존 레이어
LAYERDEPENDS_sdv = "core openembedded-layer networking-layer"

LAYERSERIES_COMPAT_sdv = "kirkstone langdale mickledore"

# vsomeip는 networking-layer의 boost 필요
